import { type NextPage } from "next";
const MainMap = dynamic(() => import("../components/MainMap"), { ssr: false });
import dynamic from "next/dynamic";

import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Leaflet Playground</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen w-screen flex-col items-center justify-center px-16 py-16">
        <MainMap />
      </main>
    </>
  );
};

export default Home;
